### ISSUE TITLE
how do i open in desktop?

### ISSUE THREAD

**Issue by bluecroc70** [tedhinklater/playnitesplashintro#1]
whenever i try and open playnite using the splash intro it always opens in fullscreen, i like how there used to be the option to play in desktop or fullscreen using the shortcut, is there any way to replicate that after using this??

**Comment by bluecroc70** [comment]
hey guys just solved my own problem, i made a file fixing this issue. its in my [repository](https://github.com/bluecroc70/Fullscreen-and-Desktop-Playnite-Splash)

**Comment by tedhinklater** [comment]
nicely done :)
